name: Build and distribute

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main # required!

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          cache: 'gradle'
          java-version: "17"

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "beta"
          cache: true

      - name: Install Dependencies
        run: flutter pub get
        shell: bash

      - name: Install Dependencies
        run: dart pub global activate flutter_distributor
        shell: bash

      - name: Build APK
        run: flutter_distributor release --name apk
        shell: bash

      - name: Build APK
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          draft: true
          token: ${{ secrets.SMS_RELEASE }}
